database_user: "{{ lookup('env', 'EMPIRE_DATABASE_USER') }}"
database_password: "{{ lookup('env', 'EMPIRE_DATABASE_PASSWORD') }}"
database_host: "{{ lookup('env', 'EMPIRE_DATABASE_HOST') }}"
github_client_id: "{{ lookup('env', 'EMPIRE_GITHUB_CLIENT_ID') }}"
github_client_secret: "{{ lookup('env', 'EMPIRE_GITHUB_CLIENT_SECRET') }}"
github_organization: "{{ lookup('env', 'EMPIRE_GITHUB_ORGANIZATION') }}"
token_secret: "{{ lookup('env', 'EMPIRE_TOKEN_SECRET') }}"
elb_sg_private: "{{ lookup('env', 'EMPIRE_ELB_SG_PRIVATE') }}"
elb_sg_public: "{{ lookup('env', 'EMPIRE_ELB_SG_PUBLIC') }}"
ec2_subnets_private: "{{ lookup('env', 'EMPIRE_EC2_SUBNETS_PRIVATE') }}"
ec2_subnets_public: "{{ lookup('env', 'EMPIRE_EC2_SUBNETS_PUBLIC') }}"
ecs_service_role: "{{ lookup('env', 'EMPIRE_ECS_SERVICE_ROLE') }}"
ecs_cluster: "{{ lookup('env', 'ECS_CLUSTER') }}"
route53_internal_zone_id: "{{ lookup('env', 'EMPIRE_ROUTE53_INTERNAL_ZONE_ID') }}"
docker_user: "{{ lookup('env', 'DOCKER_USER') }}"
docker_pass: "{{ lookup('env', 'DOCKER_PASS') }}"
docker_email: "{{ lookup('env', 'DOCKER_EMAIL') }}"
docker_registry: "{{ lookup('env', 'DOCKER_REGISTRY') }}"
database_url: "postgres://{{database_user}}:{{database_password}}@{{database_host}}/empire"

github_webhooks_secret: "{{ lookup('env', 'EMPIRE_GITHUB_WEBHOOKS_SECRET') }}"
github_deployments_environment: "{{ lookup('env', 'EMPIRE_GITHUB_DEPLOYMENTS_ENVIRONMENT') }}"
events_sns_topic: "{{ lookup('env', 'EMPIRE_EVENTS_SNS_TOPIC') }}"
