- hosts: minion
  connection: local
  vars:
    enable_streaming_logs: "{{ lookup('env', 'ENABLE_STREAMING_LOGS') }}"
  roles:
    - common
    - swap
    - docker
    - aws_ecs
    - { role: logspout, when: enable_streaming_logs == 'true' }
- hosts: controller
  connection: local
  roles:
    - common
    - swap
    - docker
    - empire
- hosts: empire_ami
  connection: local
  roles:
    - {role: build_ami, tags: ['build_ami']}
    - common
    - docker
    - aws_ecs
    - empire
